name: Sync Guides to Hex

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hex-inc/action-context-toolkit@v1
        with:
          hex_api_token: ${{ secrets.HEX_API_TOKEN }}
          publish_guides: true
          delete_untracked_guides: true
